[build]
  # relative to the repo root:
  base    = "frontend"    
  command = "npm run build" 
  publish = "dist"        

[functions]
  directory = "frontend/netlify/functions"  # if you have any Netlify Functions
